console.log("Pankiv");
let a = 25;
let b = "29Valik";
console.log(a,b);
console.log(a + b);
b = a;
console.log(a,b);
console.log(a + b);
const str = "Hello my friend!";
var ff = 100;
let bb = true;
console.log(str);
console.log(ff);
console.log(!bb);
ff = null;
console.log(ff);
let uu;
console.log(uu);
let adult = confirm("Are you have more 18 years?");
if(adult) alert("You are adult");
else alert("You aren't adult");
let n = "Valik";
console.log(typeof n); 
let s = "Pankiv";
console.log(typeof s); 
let i = 321;
console.log(typeof i);
let y = 2004;
console.log(typeof y);
let int = 123;
let bool = true;
var stri = "vvv";
let un, ss = null;
console.log(typeof int);
console.log(typeof bool);
console.log(typeof stri);
console.log(typeof un);
console.log(typeof ss);
var user = prompt("What is your name?", "Valentyn");
var email = prompt("What is your email?", "Valentyn@gmail.com");
var parol = prompt("What is your email?", "12345");
alert("Dear " + user + ", your email is " + email + ", your password is " + parol);
alert ("Hours in seconds: " + 60 * 60 + "\nDays in seconds: " + 60 * 60 * 24 + "\nMonth in seconds: " + 60 * 60 * 24 * 30);